acme_hello_homepage:
    path:     /index
    defaults: { _controller: AcmeHelloBundle:Default:inicio }
post: 
    path:     /post
    defaults: { _controller: AcmeHelloBundle:Default:post }
bienvenido:
    path:	  /bienvenido
    defaults: { _controller: AcmeHelloBundle:Default:bienvenido }
test:
    path: /test
    defaults: { _controller: AcmeHelloBundle:Default:test }

acme_hello_home: 
    path:     /home
    defaults: { _controller: AcmeHelloBundle:Default:home }
acme_id: 
    path:     /findid/{id}
    defaults: { _controller: AcmeHelloBundle:Default:buscarid }
acme_d: 
    path:     /delete/{id}
    defaults: { _controller: AcmeHelloBundle:Default:eliminarporid }
pruebaBooStrap: 
    path:     /prueba
    defaults: { _controller: AcmeHelloBundle:Default:prueba }
welcome: 
    path:     /welcome
    defaults: { _controller: AcmeHelloBundle:Default:welcome }

visa: 
    path:     /vista
    defaults: { _controller: AcmeHelloBundle:Default:vista }

